In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns
from sklearn import linear_model

In [2]:
df = pd.read_csv(r"D:\Fingertips\Python\Project\project2\Python_Linear_Regres2.csv")
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [3]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [4]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [5]:
df = df.drop(['Address','Date','Postcode','YearBuilt','Lattitude', 'Longtitude'],axis=1)
df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

In [6]:
df.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [7]:
df[['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']] = df[['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']].fillna(0)
df['Landsize'] = df['Landsize'].fillna(df.Landsize.mean())
df['BuildingArea'] = df['BuildingArea'].fillna(df.BuildingArea.mean())
df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

In [8]:
df.dropna(inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27244 entries, 1 to 34856
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27244 non-null  object
 1   Rooms          27244 non-null  int64
 2   Type           27244 non-null  object
 3   Price          27244 non-null  float64
 4   Method         27244 non-null  object
 5   SellerG        27244 non-null  object
 6   Distance       27244 non-null  float64
 7   Bedroom2       27244 non-null  float64
 8   Bathroom       27244 non-null  float64
 9   Car            27244 non-null  float64
 10  Landsize       27244 non-null  float64
 11  BuildingArea   27244 non-null  float64
 12  CouncilArea    27244 non-null  object
 13  Regionname     27244 non-null  object
 14  Propertycount  27244 non-null  float64
dtypes: float64(8), int64(1), object(6)
memory usage: 2.7+ MB

In [10]:
df['Method'].unique()

array(['S', 'SP', 'PI', 'VB', 'SA'], dtype=object)

In [11]:
df = pd.get_dummies(df,drop_first=True)

In [12]:
df

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1480000.0,2.5,2.0,1.0,1.0,202.000000,160.2564,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
2,2,1035000.0,2.5,2.0,1.0,0.0,156.000000,79.0000,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
4,3,1465000.0,2.5,3.0,2.0,0.0,134.000000,150.0000,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
5,3,850000.0,2.5,3.0,2.0,1.0,94.000000,160.2564,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
6,4,1600000.0,2.5,3.0,1.0,2.0,120.000000,142.0000,4019.0,0,...,0,1,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,6.3,4.0,1.0,3.0,593.000000,160.2564,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34853,2,888000.0,6.3,2.0,2.0,1.0,98.000000,104.0000,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34854,2,705000.0,6.3,2.0,1.0,2.0,220.000000,120.0000,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34855,3,1140000.0,6.3,0.0,0.0,0.0,593.598993,160.2564,6543.0,0,...,0,0,0,0,0,0,0,0,1,0
34856,2,1020000.0,6.3,2.0,1.0,0.0,250.000000,103.0000,6543.0,0,...,0,0,0,0,0,0,0,0,1,0

In [13]:
X = df.drop('Price',axis=1)
Y = df['Price']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=5)

In [15]:
X_train

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
4132,3,8.0,3.0,2.0,1.0,400.000000,168.0000,9264.0,0,0,...,0,0,0,0,0,0,0,0,1,0
15645,3,45.9,3.0,1.0,2.0,665.000000,110.0000,3376.0,0,0,...,0,0,0,0,0,1,0,0,0,0
13512,3,8.8,3.0,2.0,2.0,670.000000,140.0000,14577.0,0,0,...,0,0,0,0,1,0,0,0,0,0
16211,3,14.8,3.0,1.0,2.0,693.000000,160.2564,6388.0,0,0,...,0,0,0,0,0,0,0,0,1,0
14719,2,15.5,2.0,1.0,1.0,593.598993,160.2564,7630.0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3982,3,8.0,3.0,2.0,2.0,188.000000,171.0000,9264.0,0,0,...,0,0,0,0,0,0,0,0,1,0
33628,2,8.5,2.0,1.0,1.0,167.000000,160.2564,7485.0,0,0,...,0,0,0,0,1,0,0,0,0,0
26127,3,31.7,3.0,2.0,2.0,593.598993,138.0000,3553.0,0,0,...,0,0,0,0,0,1,0,0,0,0
23844,3,5.4,3.0,1.0,2.0,715.000000,160.2564,10331.0,0,0,...,0,0,0,0,0,0,0,1,0,0
3797,4,8.5,4.0,2.0,2.0,125.000000,200.0000,4898.0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [16]:
Y_train

4132     1445000.0
15645     540000.0
13512    1020000.0
16211     716000.0
14719     415000.0
           ...
3982     1467000.0
33628     660000.0
26127     389000.0
23844    1909000.0
3797     1007000.0
Name: Price, Length: 16346, dtype: float64

In [17]:
X_test

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
21049,4,8.4,4.0,3.0,2.0,593.598993,160.2564,3265.0,0,0,...,0,0,0,0,0,0,0,1,0,0
17241,2,4.6,2.0,2.0,2.0,86.000000,160.2564,7717.0,0,0,...,0,0,0,0,0,0,0,1,0,0
19257,2,10.5,2.0,1.0,1.0,100.000000,160.2564,2185.0,0,0,...,0,0,0,0,0,0,0,0,1,0
3823,1,7.7,1.0,1.0,1.0,0.000000,60.0000,8989.0,0,0,...,0,0,0,0,0,0,0,1,0,0
20534,3,38.0,3.0,2.0,2.0,306.000000,125.0000,17055.0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21988,3,25.9,3.0,2.0,2.0,410.000000,135.0000,5812.0,0,0,...,0,0,0,0,1,0,0,0,0,0
7443,1,5.5,1.0,1.0,1.0,0.000000,160.2564,11364.0,0,0,...,0,0,0,0,1,0,0,0,0,0
18385,4,11.0,4.0,1.0,1.0,499.000000,160.2564,5301.0,0,0,...,0,0,0,0,0,0,0,0,1,0
6792,2,11.8,2.0,2.0,2.0,1291.000000,160.2564,2079.0,0,0,...,0,0,0,0,0,0,0,0,0,0
22571,4,17.4,4.0,2.0,2.0,593.598993,160.2564,4704.0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [18]:
Y_test

21049    2750000.0
17241    1170000.0
19257     340000.0
3823      510000.0
20534    1010000.0
           ...
21988     547000.0
7443      340000.0
18385     890000.0
6792      665000.0
22571     575000.0
Name: Price, Length: 10898, dtype: float64

In [19]:
regression_model = LinearRegression()

In [20]:
regression_model.fit(X_train,Y_train)

LinearRegression()

In [21]:
predicted_price = regression_model.predict(X_test)
predicted_price

array([2785434.24360873, 1990808.10250574,  416073.73183214, ...,
       1265350.81646297,  868769.48664135,  814655.77770648])

In [22]:
regression_model.score(X_train,Y_train)

0.6817958133757387

In [23]:
regression_model.score(X_test,Y_test)

0.6266200647916917

In [24]:
mse = mean_squared_error(Y_test,predicted_price)
r2 = r2_score(Y_test,predicted_price)

In [25]:
print('Slope:',regression_model.coef_)
print('Intercept:',regression_model.intercept_)
print('Root Mean Square Eroor:',mse)
print('R2 Score:',r2)

Slope: [ 2.59717664e+05 -4.59394518e+04 -8.57532106e+04  1.23380161e+05
  4.42253725e+04  1.87073032e+00  3.15441531e+02  1.38960155e+00
  2.00430279e+05 -4.88912695e+04 -1.35447822e+05  2.93025016e+05
  1.26413597e+05  1.83238139e+05  2.03925652e+05 -1.26486386e+05
 -1.67833255e+05 -5.94670874e+04  3.42104333e+04 -8.84566826e+04
 -8.69339699e+04 -4.00326368e+04  1.02133433e+05 -2.52988183e+05
 -3.18275247e+04 -2.52474666e+05  8.26112228e-08 -1.37814680e+05
  9.94866110e+04  3.20102469e+04  1.35729732e+05 -2.05215252e+04
  2.08433376e+05  2.98284212e+04  2.06871074e+05 -3.43554995e+05
  7.84101775e+04 -1.32600146e+04 -1.72866881e+03  2.95498823e+05
  1.45119356e+05 -1.77504920e+05 -5.65045105e+04  2.18616029e+05
  1.44986980e+05  4.29310733e+05  1.98870789e+05 -1.24628417e+05
 -8.68727504e+04  3.41864201e+05 -1.04442630e+05 -7.11106077e+04
  1.25829903e+04  1.19988963e+05  4.42548173e+04  2.17062371e+04
  1.08889837e+02  1.40338670e-07 -1.98474967e+05  1.00919174e+05
 -1.54140626e+05 -3.46409158e+04 -2.30215564e+05 -3.20008160e+05
 -5.21798644e+04 -2.50131577e+04 -7.21291205e+04  7.24139039e+04
 -1.57976803e+05  4.40159805e+05  1.08874684e+05  2.94419847e+05
  2.03931922e+04 -1.99663736e+05  3.52042247e+05 -1.49187300e+05
 -2.20136920e+05  5.72933894e+04  8.52348118e+04  3.95741110e+04
 -9.86610504e+04  3.07264319e+05 -2.03509092e+04 -2.29948856e+05
 -9.76597975e+04 -3.27024593e+05  2.65009733e+04 -1.97884903e+05
  6.76311577e+04  3.16397784e+05 -9.77677451e+04 -1.84232673e+05
 -7.15543056e+04 -4.17440698e+04 -1.13072276e+05 -3.09381641e+04
 -3.61646717e+04  1.32247806e-06 -6.18237786e+04  3.60549065e+03
 -4.46281123e+03  6.57709531e+04 -4.87452581e+04 -3.78113728e+04
  4.94819524e+04 -2.67752810e+05  5.79356914e+04  4.15545518e+04
  1.03209004e-06  5.50684549e+05 -1.29811537e+04 -1.61214727e+04
 -1.47070706e+05 -2.62825680e+05  1.58608401e+05 -1.72195129e+05
 -2.78807487e+05 -1.38520218e+04  2.30427943e+04  1.02060540e+05
 -3.56645179e+05 -5.00074709e+05  3.54025950e+05  1.63257694e+05
  2.81982590e+05  5.96372265e+04 -5.41403243e+04 -2.80605669e+05
  1.60623667e+04 -3.20696046e+05 -2.26680118e+05 -1.47467201e+04
  1.11658077e+05  4.39013144e+04 -9.18576248e+03 -1.07574712e+05
  6.14585588e-07  1.60111740e+05 -6.30105027e+04  1.68860581e+05
 -2.29716534e-07  1.91346482e+05  2.61559708e+05 -1.15370209e+05
 -2.22703932e+04 -6.22740825e+04  2.15245582e+05 -1.43345982e+04
  4.33088087e+05 -2.72943120e+05  5.39269839e+04  1.87693437e+05
 -2.49803002e+05 -1.91031575e+04 -9.56114638e+04  2.93525241e+05
 -6.23806180e+04 -2.26278471e+05  1.06916459e+04  5.76371333e+04
 -1.11439272e+05  2.03153249e+05  1.40809465e+05 -2.54996555e+05
 -5.46851844e+04 -3.00141530e+05 -1.18584962e+05  4.93605776e+05
 -2.11985772e+05  1.12691558e+05 -1.42875563e+05 -3.74201045e+05
 -4.51331447e+05 -1.11967461e+05 -1.90359469e+04  3.71968239e+04
  8.66982352e+04 -1.76267120e+05 -2.54264618e+05 -4.20869043e+04
  5.12604362e+05 -1.14923333e+05  2.33198485e+05 -1.48232920e+05
  1.57865059e+05 -2.78728409e+04  9.53557814e+04  5.43035305e+04
 -7.35504107e+04 -9.11475092e+04 -5.72796639e+04 -1.78758018e+05
  6.68061861e+04  1.00259443e+05 -1.09506452e+05 -1.65264975e+05
  3.89612900e+04  1.71273518e+04  1.49256284e+04 -1.34508591e+05
 -1.03163570e+05  1.61214768e+05  9.36354522e+03 -2.71752211e+05
 -6.14152730e+04  1.44433327e+05 -4.14554961e-07  8.73408095e+03
 -6.44429903e+04  3.70395524e+05 -6.41066935e+04 -8.43193109e+03
  2.30387731e+05 -5.94164907e+04  1.56694593e+04  2.83737662e+04
  1.01748873e+05 -1.43592069e+05  1.06096580e+05  1.03830800e+05
 -7.10025166e+04  5.84591451e+05 -8.23500507e+04  1.31165509e+05
  5.48919419e+04 -1.22265558e+04 -7.47870372e+04 -2.26963432e+05
  8.26673354e+04 -1.58612046e+05 -1.09500759e+05  1.14307853e+05
 -3.71145314e+04  1.35272049e+05  5.45966348e+04 -1.09706089e+04
  7.76649546e+04  1.38179327e+05 -3.76293805e+04  9.86063461e+04
  5.57664565e+04 -4.94452286e+04  5.10720296e+05  1.84412565e+05
  1.29145380e+04 -6.31798252e+04  4.89697217e+04  1.34147768e+04
 -5.18370007e+04 -3.24371173e+05  8.36350504e+04  7.56985906e+04
  2.78170604e+05  2.18423444e+05  4.32924656e+05 -5.24031945e+04
  1.85313270e+05  4.49081526e+05  2.45455087e+05 -1.41169914e+05
 -3.64081941e+04 -2.67709939e+05 -7.73910809e+04  4.53295016e+05
  1.41357393e+05 -6.91308785e+04  6.97141179e+03  1.17569489e+05
  2.82904553e+04  1.12440281e+05 -7.35141719e+04 -1.50338108e+05
  6.08703256e+05 -2.41038362e+05 -2.24796988e+05 -5.97993885e+04
 -2.23199002e+05  1.32605530e+05  1.05139431e+05 -1.74259923e+05
  1.37384191e+05 -6.09748677e+04  2.04986009e+04 -1.87415571e-06
 -1.81938523e+05 -7.03627378e+04 -1.83496199e+05 -7.02805836e+04
 -7.35944263e+04 -3.93694176e+05 -5.30815766e+04 -1.44801460e+05
 -1.14115420e+05  8.27058819e+04 -3.45189330e+05 -1.30395501e+05
  4.60822412e+04 -1.77498697e+05  4.50613776e+05  6.18112164e+04
 -2.83214350e+04 -1.36816999e+05 -2.17606291e+04  4.73181732e+04
  1.41316225e+04 -9.75064233e+04 -6.42558071e+04  2.48042493e+03
  1.53246404e+05 -1.55664898e+05  2.17388215e+05 -3.42186183e+03
  6.10072385e+04  1.86474027e+05 -1.80483788e+04 -1.64479365e+03
  7.85038224e+04  5.67535924e+04 -8.29281570e+04 -7.49727598e+04
 -3.90284219e+05  1.50192681e+05  2.48604663e+05 -2.95422829e+05
 -2.19829985e+05  3.61403820e+05 -1.89273511e+05 -2.80932159e+04
  4.01749303e+04 -1.21349007e+05 -2.82903655e+05 -1.18446578e+05
 -1.62651877e+05 -5.31189660e+04  3.87640016e+04 -8.02244068e+04
 -1.57941390e+05  4.58811227e+04  3.86329822e+05 -2.30432060e+05
  3.01258672e+05  7.72561973e+04 -1.73158881e+05  1.38426001e+05
 -5.76436748e+04  3.80898089e+05 -9.72660748e+04  6.96600182e-08
  4.81468665e+04 -3.72284039e+03  2.05863034e-06 -2.73480763e+05
 -4.80066399e+05  6.61591528e+04  3.72963611e+03  2.88331332e+04
 -1.61603684e+03  3.06717266e-06  1.27995575e+05  1.22056574e+05
  4.61577206e+05 -2.78825686e+05  5.31032094e+05  1.30649527e+05
 -1.87510159e-06 -1.77893855e+05  1.89531342e+05 -3.41528157e+05
  1.64553159e+05  2.13165528e+05 -9.35472773e+04 -2.48700176e+05
  1.55595255e+05  3.60690710e+05  1.58020793e+05  1.93390033e+04
  2.98328673e+05  1.04223021e+05  5.44601606e+04  3.55570225e+05
 -8.34614280e+04  1.46096068e+05 -5.23568582e+04  6.36944428e+04
  2.64115791e+05 -8.97241007e+04  2.22882954e-06  1.20775076e-06
  5.39554733e+04  1.74282318e+05  9.18572866e+04  2.57074134e-07
  1.85321567e+05 -8.75001728e+04  1.34311386e+05 -3.27499570e+05
 -5.10921287e+04  7.20305688e+04  1.55829118e+05  9.71747911e+04
 -2.47210583e+04  1.25865045e+05 -1.83569531e+05 -2.01939838e-06
  7.76953034e+04 -1.08331014e+05  4.09007771e-06  3.66975461e+05
 -3.28385795e-07  7.63639033e+04 -1.72154459e+05  6.06160797e+05
  7.91936385e+04  1.32975341e+05  1.37007222e+05  3.35087745e+05
  6.22418595e+04 -2.16772598e+05  2.22949148e+05 -2.67155408e+05
  1.41323925e+05 -2.52062573e+05  6.06027556e+04 -2.14816179e+05
  2.73818194e+05 -9.86918878e+04  2.20834456e+05  1.19612905e+05
  2.67995104e+05  1.26220992e+05 -3.44775617e-06 -3.08340136e+04
 -2.96795042e-06 -2.56638935e+04  9.77446221e+04  6.76309191e+04
  4.56275540e+04 -1.41565810e+05  1.33351598e+06  1.91270285e+05
 -1.04052099e+05  1.11946528e+05 -8.23663897e+04 -1.76458343e-06
 -1.35716168e+05 -1.82523426e+05 -7.35147005e+04  4.14915597e+04
  8.27334630e+04  3.58806972e+05  6.09162443e+04  9.65967195e+04
  1.16218001e+05  1.02235403e+05  1.37372406e+05  7.23092302e+04
 -3.67919890e+04 -9.31525363e+04  3.24565917e-07  1.59171412e+06
  9.11002109e+04  1.40748886e+05  3.27096067e+04  4.37017542e+04
  1.78548474e+05 -3.00043499e+05 -4.24485326e+05 -3.21076217e+03
  8.71572411e-07  2.03162199e-06  9.03750129e+04  1.17298749e+05
  4.23328694e+04  5.33659167e+05  6.09477010e+04  1.77288433e+06
  7.30782796e+03 -2.14551344e+05  8.46175124e+04 -7.03590209e+04
 -2.17427176e+04 -5.62919116e+04  8.03520176e+03 -8.97070836e+04
  3.36402191e+05  8.20053681e+04  6.19583424e+05  1.26145780e+05
  9.66155128e+04  1.19678589e-06  7.35290699e+03  1.93793819e+04
 -3.46129863e+04 -1.91248627e+05  4.08155756e-07  6.05388630e+04
  9.93673482e+04  7.89268444e+04  1.44175430e+05  3.17719119e+04
 -2.39058863e-07 -1.11156260e-06  1.91934682e+04  1.46572213e+04
  4.48656466e+05 -1.50673441e-06 -2.56212661e-06  6.72648640e+05
 -1.72308930e+05  1.49571572e+05  2.89902908e+05 -3.19282660e+04
 -1.81221612e+05 -1.28800988e+05  7.81247540e+04 -3.27612511e+04
  6.41870062e+05 -1.54524601e+05  3.23585651e+05  1.59302726e-06
 -1.82777750e+04  1.94292145e+05  4.26147738e+04 -6.32304315e+03
  3.98329687e+05  1.05699005e+05  2.88814910e+05 -6.14974965e+05
 -6.57726425e+02  6.51130231e+04 -3.67702855e+04  1.25186481e+05
 -6.32618689e+04 -1.09533319e+05 -4.31051225e+03  7.79628504e+04
  3.52474315e+05  1.34843689e+04  6.12967081e+04  3.15620750e+05
  1.81036427e+05 -1.23561684e+05  8.83859944e+04 -1.66577055e+05
 -8.39828096e+04  8.78280141e+04  1.33273752e+05 -1.49733378e+05
 -8.44027432e+04  1.81587417e+05  4.30566017e+03 -8.35734261e+04
  1.69315915e+05  1.06365157e+05  2.18208879e-06  2.39030273e+05
  1.44702408e+05 -2.14287542e+05  1.22630233e+05  7.49186643e+04
  1.14045593e+05 -6.79250352e+04  6.04535020e+04 -2.93389472e+04
  7.59256368e+04  8.53581289e+05  3.87919831e+04  1.59205212e+04
  2.37431424e+05  4.62741790e+04  3.04577034e+05  7.15099436e+04
 -2.52128239e+05  2.01453894e+05  3.39426768e+05  3.52226099e+04
  6.55449867e+03  8.36318751e+04  6.10466034e+04 -9.40611392e+04
 -1.90439100e+05  3.33097553e+04 -1.32577175e+04  1.18677660e+04
 -1.85272074e-06  1.15770387e+05  1.00905864e+05  2.56031303e+05
  2.71324159e+05  2.53818561e+05  8.23463779e-07 -5.14939053e+04
  7.82771125e+04  6.32370160e+04 -2.33942408e+04 -2.10839789e-06
  1.69686373e+05  8.49876327e+04  3.86702595e-07  1.69545158e+05
 -5.70622460e+05 -3.40273447e+05 -3.81280527e+04  1.09987728e+05
 -8.66139304e+04  1.23124160e+05  1.94039040e+05  2.90123717e+05
  5.06163125e+04  2.40532184e+04 -1.72080999e+05  2.02190293e+04
 -7.26607043e+04 -5.14758546e+05  4.01826522e+05  3.82024695e+04
  3.66637484e+04  1.28090323e-06  7.55651755e+04  2.17877107e+04
  4.77681169e-07  2.02607369e+04 -1.00545420e+05  3.67857147e+05
 -1.99789179e+05  3.04700525e+05 -3.28672374e+05  1.35720691e+05
  2.01962269e+05  1.92530085e+05 -6.32993868e+05  1.47678976e+05
 -4.04004083e+05  5.29143478e+04 -1.49211259e+05 -1.68418644e+04
 -6.87432475e-07  1.60164580e+05 -4.38627733e+05  4.78656578e+05
 -5.54835424e-07  2.04205245e+05 -5.24972780e+04 -6.86995918e-08
  3.38028325e+04 -2.64887687e+05  4.16489642e+04 -2.08303366e+05
 -1.34446600e-06 -1.61002390e-07 -1.18214912e+05  2.87851227e+05
 -7.66609369e+03 -1.70697834e+04 -4.90497448e+05 -1.18091391e+05
  1.57567655e+05  3.34891292e+04 -1.60252088e+05  1.99187278e+04
  3.22243781e+05 -1.43543692e+05  1.34656893e+05  1.04588177e+06
 -1.39855672e+05  0.00000000e+00 -4.99570178e+04 -2.39808319e+05
  9.03014585e+04 -1.36590304e+03  6.68967287e+05  5.79185613e+04
  6.03410524e+04  0.00000000e+00  2.62415661e+05 -3.41778346e+05
 -1.31283856e+05  2.22886218e+05 -4.20868408e+04  1.12417247e+05
  8.56554129e+04  2.11021596e+05 -9.66692977e+04 -2.40755306e+03
  3.60471024e+04 -5.97551977e+04 -3.06702676e+05  6.11696881e+04
  4.19593689e+03  4.29950714e+04  3.90081127e+03  1.78081545e+05
  2.52958015e+05 -7.27729236e+04  0.00000000e+00  0.00000000e+00
  6.15947154e+05  7.18844871e+04  0.00000000e+00  1.20298812e+05
  0.00000000e+00 -2.28902977e+05  0.00000000e+00  3.43982570e+05
 -8.47778056e+04  4.16293591e+05  3.23458324e+05 -2.26544149e+05
  2.79371406e+05  1.85833694e+05 -5.01767064e+03  3.78273206e+05
  1.10215408e+05 -3.68539935e+04 -9.88240609e+04 -8.44702078e+04
  1.92673840e+05  4.91824898e+04  5.98288410e+05  7.74240006e+04
 -1.65285940e+05  8.59319788e+04  1.54431131e+04 -1.30275365e+05
  1.50192681e+05  4.60033843e+04 -1.12098644e+04  0.00000000e+00
 -7.59021819e+04 -5.54799159e+04  1.18475464e+05  2.74188980e+05
  7.88862234e+04  1.41751369e+04 -2.20473893e+05  9.14220564e+03
  4.17913619e+04  2.31462602e+05 -2.22632023e+05  3.02309725e+05
  1.15348737e+05  7.79187152e+03 -1.97747714e+05  1.42705630e+05]
Intercept: 770634.0910922963
Root Mean Square Eroor: 157706553926.4732
R2 Score: 0.6266200647916917

In [26]:
ridge_reg = Ridge(alpha=50,max_iter=50)
ridge_reg.fit(X_train,Y_train)

Ridge(alpha=50, max_iter=50)

In [27]:
ridge_reg.score(X_train,Y_train)

0.6605721514890827

In [28]:
ridge_reg.score(X_test,Y_test)

0.6202920552279938

In [29]:
import warnings
warnings.filterwarnings('ignore')

In [30]:
lasso_reg = Lasso(alpha=50,max_iter=100)
lasso_reg.fit(X_train,Y_train)

Lasso(alpha=50, max_iter=100)

In [31]:
lasso_reg.score(X_train,Y_train)

0.6773196908923056

In [32]:
lasso_reg.score(X_test,Y_test)

0.6282750086553057